### ISSUE TITLE
Client nicht installiert. Reiter trotzdem da...

### ISSUE THREAD

**Issue by olien** [rkemmere/project_manager#1]
![image](https://user-images.githubusercontent.com/330516/46518997-13951180-c877-11e8-9dcc-e59594392bd0.png)

![image](https://user-images.githubusercontent.com/330516/46519004-1bed4c80-c877-11e8-9775-75dccbea3cc2.png)

**Comment by rkemmere** [comment]
Plugin als Plugin ist nur ein Demoplugin. Wir nehmen das erstmal raus und machen es später als Demoplugin für Entwickler rein.
