### ISSUE TITLE
Cronjobs automatisch bei der Installation anlegen

### ISSUE THREAD

**Issue by olien** [rkemmere/project_manager#13]
Spricht irgendetwas dagegen?

**Comment by rkemmere** [comment]
Nein spricht nichts dagegen. Ich schau mir das mal an. Kann man ja direkt per SQL Insert machen oder?

**Comment by olien** [comment]
Ja. Das sollte problemlos gehen (habe ich z.B. mit MediaManager Typen in der Modulsammlung gemacht)

**Comment by rkemmere** [comment]
Add in 1.1.0
