### ISSUE TITLE
"Letze Änderung" in der (Server)Übersicht

### ISSUE THREAD

**Issue by olien** [rkemmere/project_manager#14]
![image](https://user-images.githubusercontent.com/330516/46601763-7b08c680-caee-11e8-9a47-ef8180b64250.png)

Ist das die "Letze Änderung" des Eintrages oder die "Letze Änderung" auf/an der Webseite (fänd ich sinnvoller).

**Comment by rkemmere** [comment]
Die "Letzte Änderung am Datensatz" Es kann ja auch sein, das die Seite nicht erreichbar war, oder einen 500er zurückgegeben hat.

**Comment by olien** [comment]
ok... im idealfall seteht dann immer der gleiche wert dort...
würde die info nicht auf der detailseite reichen?

Die Info ist ja dann nur interessant wenn etwas nicht funktioniert hat - richtig?

**Comment by rkemmere** [comment]
In der Übersicht ist nun die letzte Änderung im CMS.

**Comment by AWqxKAWERbXo** [comment]
Die Idee "letzte Änderung" war, um festzustellen, ob der Abruf des hello/project_manager-Addon auch aktuell ist und nicht aus irgendwelchen Gründen nicht erfolgte.

**Comment by rkemmere** [comment]
Sollte der Durchlauf nicht geklappt haben, Wird jetzt als Status ein Ausrufezeichen angezeigt. Ist der rot darf man im Detail schauen warum.
