### ISSUE TITLE
minimale (Wunsch)PHP Version

### ISSUE THREAD

**Issue by olien** [rkemmere/project_manager#16]
In den Settings eine minimale Wunsch PHP Version angeben.

In der Übersicht dann alle kleineren PHP Versionen kenntlich machen...

![image](https://user-images.githubusercontent.com/330516/46604637-2c135f00-caf7-11e8-8513-4df88ea480c5.png)

**Comment by rkemmere** [comment]
Dazu ist dann eine Einstellungen Seite notwendig. Die vielleicht auch die anzuzeigenden Spalten konfigurier machen würde.

**Comment by olien** [comment]
ok. vielleicht wäre es ja auch "übergangsweise" dort einzutragen wo die url und der rest für ein projekt eingetragen werden... PHP > als

**Comment by rkemmere** [comment]
Kommt in der nächsten Version
