### ISSUE TITLE
Farbkonzept

### ISSUE THREAD

**Issue by olien** [rkemmere/project_manager#17]
Irgendein Konzept hinzufügen, damit man schenll erkennen kann welche Seiten ok sind und welche nicht.

z.B.:

- Alles ok 
- Syslog Einträge vorhanden
- PHP Version veraltet
- Seite nicht erreichbar
- Updates vohanden

![image](https://user-images.githubusercontent.com/330516/46604819-e014ea00-caf7-11e8-87dc-389dd757b1d0.png)

evtl. könnte ja auch die ganze zeile (leicht) eigefärbt werden... (wenn es nicht zu bunt wird)

**Comment by rkemmere** [comment]
Kommt in der nächsten Version!
