### ISSUE TITLE
Möglichkeit nur das Projektmanager Addon zu nutzen für einen Benutzer

### ISSUE THREAD

**Issue by olien** [rkemmere/project_manager#8]
Ich habe eine Rolle angelegt, die nur die Rechte hat das ProjektManager Addon zu benutzen.
Leider wird nur die Profilseite des Nutzers angezeigt.

Sinnvoll wäre es ja ein REDAXO Projekt nur für dieses Addon anzulegen.
Mehr muß dann der Nutzer nicht sehen.

**Comment by rkemmere** [comment]
Eingebaut in Hauptversion 1.1.0
