### ISSUE TITLE
Ideen zur Verlinkung

### ISSUE THREAD

**Issue by olien** [rkemmere/project_manager#9]
![image](https://user-images.githubusercontent.com/330516/46534651-2b858900-c8a9-11e8-87d9-5512f00e8d35.png)

**Comment by rkemmere** [comment]
Vorne das Icon und die Domain selber sollen auf die Domain leiten. Projektname soll die Detailview sein.
Führe mal den Favicon Cronjob aus, dann sollte das Icon sich ändern.

Fix für den Favicon Folder ist in 1.0.8

**Comment by olien** [comment]
Funktioniert (und sieht klasse aus)
